### PR TITLE
Add 4 new products

### PR DESCRIPTION
**Pull request by Hywan**
Please, review these new products @hoaproject/hoackers!

### CODE REVIEW

**Comment by CircleCode** [comment]
for those wanting to see the products directly:

# Hoa's hoodie 2.0:

Hoa's hoodie 2.0

# Hoa's bag:

Hoa's bag

# Hoa's isothermal mug

Hoa's isothermal mug

# Hoa's wide mug

Hoa's wide mug

**Comment by CircleCode** [comment]
Here come my comments:
- Hoa's hoodie 2.0:
  
  I find it difficult to see in which direction the text should be read, so that it becomes difficult to read "HOA"
- Hoa's bag:
  
  it seems fine, but I wouldn't add the mini logo inside of the "O"
- Hoa's isothermal mug:
  
  same comment as for the hoodie
- Hoa's wide mug:
  
  seems fine

**Comment by Hywan** [comment]
Logo inside the logo is a concept developed here: https://www.brandbrothers.fr/fr/hoa_typographie_identite. I like it because it reminds the `ArrayAccess` (to access to Hoa).

**Comment by CircleCode** [comment]
So I find the proposal from https://www.brandbrothers.fr/thumbs/1066x834/ref_hoa10.jpg more efficient: rotated logo is truncated so that we do not try to read it, and mini logo is fully readable.
Thus mini logo size could be increased.

**Comment by Hywan** [comment]
We can't truncate the logo on the product because of the print constraints.

**Comment by CircleCode** [comment]
it can't be trucated at the hoodie or the mug edges, I understand it.
But it can be truncated "by design" (not sure this is really clear?)

**Comment by Hywan** [comment]
I understand. I will try to do that. Need more time.

**Comment by CircleCode** [comment]
:+1: 
Also, have you considered using the horizontal logo on the isothermal mug?

**Comment by Hywan** [comment]
@CircleCode Yes but since this is a cone, I am not sure how the logo will be skewed.

**Comment by Hywan** [comment]
We got very few feedbacks from @hoaproject/hoackers. Please vote!

**Comment by jemdev** [comment]
I'll be on neutral mode on this new logo.

But my opinion on the vertical version : it must be readable, so this needs first a reverse at 180°, and then a rotate 90° for each « letter », something like this : 

```
|   |
 ¯¯¯
 ___
|   |

 ___
|   |
|   |
 ¯¯¯
 ___
|   |
 ___
|   |

```

**Comment by CircleCode** [comment]
> Yes but since this is a cone, I am not sure how the logo will be skewed.

I suppose it could be skewed a first time so that the printing on the cone could be ok, but I have no idea how it should be transformed…

**Pull request merged**
